catalog
catalogDescription

^ 
'nagare-logger
=============

Nagare is a new flexible logger which connects to fluentd (http://fluentd.org).

* Simple log interfaces with reliable backend
* Semi-structured logging (Not only String, you can store structured records in log)
* Portable (runs on VW, Squeak, and Pharo)

For more info, please see the github project page (https://github.com/mumez/nagare-logger).

'